---
waifu2x_caffe:
  path:
  input_extention_list:
  output_extention:
  mode: noise_scale
  scale_ratio:
  scale_width:
  scale_height:
  noise_level: 3
  process: gpu
  crop_size: 128
  output_quality: -1
  output_depth: 8
  batch_size: 1
  gpu: 0
  tta: 0
  input_path:
  output_path:
  model_dir:
  crop_w:
  crop_h:
waifu2x_converter:
  path: /opt/waifu2x-cpp/
  output-format:
  png-compression:
  image-quality:
  block-size:
  disable-gpu:
  force-OpenCL:
  processor: gpu
  jobs:
  model-dir:
  scale-ratio:
  noise-level: 3
  mode: noise-scale
  silent: true
  output:
  input:
waifu2x_ncnn_vulkan:
  path: 
  v:
  i:
  o:
  n: 2
  s: 2
  t: 400
  m: models-cunet
  g: 0
  j: "1:2:2"
anime4k:
  path:
  java_path:
ffmpeg:
  ffmpeg_path: /usr/bin/
  video_to_frames:
    output_options:
      "-qscale:v":
      "-pix_fmt": rgba64be
    "-hwaccel": cuda
    "-y": true
  frames_to_video:
    input_options:
      "-qscale:v":
      "-qscale:a":
      "-f": image2
    output_options:
      "-vcodec": h264_nvenc
      "-crf": 17
      "-b:v":
      "-pix_fmt":
    "-hwaccel": cuda
    "-y": true
  migrating_tracks:
    output_options:
      "-map":
        - 0:v?
        - 1:a?
        - 1:s?
        - 1:d?
        - 1:t?
      "-c": copy
      "-pix_fmt":
    "-hwaccel": cuda
    "-y": true
video2x:
  video2x_cache_directory: /home/shelltear/cachevideo2x/
  image_format: png
  preserve_frames: false
